# Generated by Django 2.0.5 on 2018-05-13 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('WAITING_REGISTRATIONS_OPENING', 'WAITING_REGISTRATIONS_OPENING'), ('WAITING_PLAYERS', 'WAITING_PLAYERS'), ('WAITING_GAME_LAUNCH', 'WAITING_GAME_LAUNCH'), ('WAITING_PLAYER_INPUT', 'WAITING_PLAYER_INPUT'), ('PROCESSING_PLAYER_INPUT', 'PROCESSING_PLAYER_INPUT'), ('PLAYER_WINS', 'PLAYER_WINS'), ('FINISHED', 'FINISHED')], default='WAITING_REGISTRATIONS_OPENING', max_length=200)),
                ('genre', models.CharField(choices=[('HF', 'HF'), ('FH', 'FH'), ('HH', 'HH'), ('FF', 'FF')], default='HF', max_length=2)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_genre', models.CharField(max_length=2)),
                ('_preparation', game.models.JsonField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='game.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
