# Generated by Django 2.0.5 on 2018-05-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('HF', 'HF'), ('FH', 'FH'), ('HH', 'HH'), ('FF', 'FF')], default='HF', max_length=2),
        ),
    ]
