# Generated by Django 2.0.5 on 2018-05-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20180511_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('WAITING_REGISTRATIONS_OPENING', 'WAITING_REGISTRATIONS_OPENING'), ('WAITING_PLAYERS', 'WAITING_PLAYERS'), ('WAITING_GAME_LAUNCH', 'WAITING_GAME_LAUNCH'), ('WAITING_PLAYER_INPUT', 'WAITING_PLAYER_INPUT'), ('PROCESSING_PLAYER_INPUT', 'PROCESSING_PLAYER_INPUT'), ('PLAYER_WINS', 'PLAYER_WINS'), ('FINISHED', 'FINISHED')], default='WAITING_REGISTRATIONS_OPENING', max_length=200),
        ),
    ]
